# Generated by Django 4.0 on 2022-01-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=35)),
                ('plistedby', models.CharField(max_length=25)),
                ('pname', models.CharField(max_length=200, null=True)),
                ('psize', models.CharField(max_length=10, null=True)),
                ('pcolor', models.CharField(max_length=25, null=True)),
                ('pocasion', models.CharField(max_length=25, null=True)),
                ('pfit', models.CharField(max_length=25, null=True)),
                ('pfabric', models.CharField(max_length=30, null=True)),
                ('preversible', models.CharField(max_length=5, null=True)),
                ('pidealfor', models.CharField(max_length=15, null=True)),
                ('pmanufacturer', models.CharField(max_length=120, null=True)),
                ('ppacker', models.CharField(max_length=120, null=True)),
                ('potherdetail', models.CharField(max_length=500, null=True)),
                ('psellingprice', models.CharField(max_length=10, null=True)),
                ('pdiscount', models.CharField(max_length=120, null=True)),
                ('pimg1', models.ImageField(null=True, upload_to='products/clothes/')),
                ('pimg2', models.ImageField(null=True, upload_to='products/clothes/')),
                ('pimg3', models.ImageField(null=True, upload_to='products/clothes/')),
                ('pimg4', models.ImageField(null=True, upload_to='products/clothes/')),
                ('pimg5', models.ImageField(null=True, upload_to='products/clothes/')),
                ('pimg6', models.ImageField(null=True, upload_to='products/clothes/')),
                ('pimg7', models.ImageField(null=True, upload_to='products/clothes/')),
                ('pimg8', models.ImageField(null=True, upload_to='products/clothes/')),
                ('pactive', models.IntegerField(default=1)),
                ('pdel', models.IntegerField(default=0)),
            ],
        ),
    ]
