# Generated by Django 4.0 on 2022-01-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcloth_pimg1_alter_productcloth_pimg2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcloth',
            name='pimg1',
            field=models.ImageField(blank=True, null=True, upload_to='products/clothes/'),
        ),
        migrations.AlterField(
            model_name='productcloth',
            name='pimg2',
            field=models.ImageField(blank=True, null=True, upload_to='products/clothes/'),
        ),
    ]
